import type { Product } from "@/lib/api";

export const fallbackProducts: Product[] = [
  {
    id: "1",
    slug: "caffeine-under-eye-serum",
    name: "5% Caffeine Under Eye Serum",
    tagline: "Awaken tired eyes",
    description: "5% caffeine + retinol + hyaluronic acid eye serum.",
    volume: "15ml",
    priceAed: 149,
    category: "Eye Care",
    keyIngredients: ["5% Caffeine", "Retinol", "Hyaluronic Acid"],
    features: ["Anti-Puffiness", "Dark Circles"],
    usage: "Apply morning and evening to under-eye area.",
    benefits: [],
  },
  {
    id: "2",
    slug: "bakuchiol-anti-aging-serum",
    name: "Bakuchiol Anti-Aging Serum",
    tagline: "Nature's retinol alternative",
    description: "1.3% bakuchiol peptides + vitamin C.",
    volume: "30ml",
    priceAed: 189,
    category: "Face Serum",
    keyIngredients: ["Bakuchiol", "Vitamin C"],
    features: ["Anti-Aging", "Brightening"],
    usage: "Apply to face and neck after cleansing.",
    benefits: [],
  },
  {
    id: "3",
    slug: "ghk-cu-barrier-repair-serum",
    name: "GHK-Cu Barrier Repair Serum",
    tagline: "Repair your skin barrier",
    description: "GHK-Cu + ectoin + hyaluronic acid.",
    volume: "30ml",
    priceAed: 199,
    category: "Face Serum",
    keyIngredients: ["GHK-Cu", "Ectoin"],
    features: ["Barrier Repair", "Hydrating"],
    usage: "Apply morning or evening before moisturizer.",
    benefits: [],
  },
];
